### ISSUE TITLE
HTTP API exception when checking not existing channel

### ISSUE THREAD

**Issue by nodaschi** [tlaverdure/laravel-echo-server#133]
Hi.

GET /apps/:APP_ID/channels/:CHANNEL_NAME

throws exception when channel does not exist.

TypeError: Cannot read property 'length' of undefined
    at HttpApi.getChannel (/usr/local/lib/node_modules/laravel-echo-server/dist/api/http-api.js:47:37)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/api/http-api.js:15:99
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:365:14)
    at paramCallback (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:401:21)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/server.js:67:13
    at paramCallback (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:404:7)
    at param (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:384:5)
    at Function.process_params (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/local/lib/node_modules/laravel-echo-server/node_modules/express/lib/middleware/init.js:40:5)

**Comment by tlaverdure** [comment]
This should be fixed now at 1.3.1
