### ISSUE TITLE
Using in homestead virtual machine throws error.

### ISSUE THREAD

**Issue by Dastur1970** [tlaverdure/laravel-echo-server#16]
I'll keep it short. I'm using Laravel homestead. At first, I was being dumb and I was trying to start the server outside of the vm. It would startup normally, my site just wouldn't be able to access it. When I finally started running it in the vm, I got this stack trace:
```
/home/vagrant/Projects/Blog/node_modules/laravel-echo-server/dist/echo-server.js:159
    emitPresenceEvents(socket, channel, members, member, action = null) {
                                                                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vagrant/Projects/Blog/node_modules/laravel-echo-server/dist/index.js:2:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Is this something I'm doing? Thanks.

**Comment by tlaverdure** [comment]
Looks like a node issue with setting defaults in function parameters. Will be fixed in next release.

**Comment by jonnywilliamson** [comment]
@Dastur1970

Yeah main cause of this is the fact that homestead comes with node 5 installed and that doesn't support parameter defaults. 

Upgrading to node 6 will fix that, but might cause you other issues with gulp etc. 

Probably best to hold off for a little while until @tlaverdure releases a newer version soon.
