### ISSUE TITLE
node_sqlite3.node not found after fresh installation

### ISSUE THREAD

**Issue by cre8** [tlaverdure/laravel-echo-server#172]
I wanted to install the package and the installation went fine. But when I try to call `laravel-echo-server` in my command line, it throws me this error:

Error: Cannot find module 'C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\database\sqlite.js:2:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by cre8** [comment]
A fresh new install with `npm remove` did the trick....
