### ISSUE TITLE
Error: %1 is not a valid Win32 application?

### ISSUE THREAD

**Issue by xlkit456852** [tlaverdure/laravel-echo-server#183]
I use Homestead in Win10 system (x64) to install laravel-echo-server.
After fresh install, i run laravel-echo-server init,and got this error . I have trided to remove node-sass and reinstall it ,but still the same result :

```
E:\Myenv3\wwwroot\realtime>laravel-echo-server init
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\E:\nodejs\node_global\node_modules\laravel-echo-server\node_modules\sqlite3\lib\binding\node-v51-win32-x64\node_sqlite3.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\laravel-echo-server\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\nodejs\node_global\node_modules\laravel-echo-server\dist\database\sqlite.js:2:15)
    at Module._compile (module.js:571:32)
```

**Comment by tlaverdure** [comment]
Is this issue still occurring?

**Comment by gustavomurad** [comment]
Try npm rebuild

**Comment by alexykouakou** [comment]
You get this error because your laravel echo server is broken.
Go to `E:\nodejs\node_global\node_modules\` (the path in your console) and delete **laravel-echo-server** folder
In E:\nodejs\node_global\ delete **laravel-echo-server** and **laravel-echo-server.cmd** files.
Verify your connection speed and run `npm install -g laravel-echo-server` again
Problem solved !

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
