### ISSUE TITLE
Cannot find module node_sqlite3.node

### ISSUE THREAD

**Issue by thomabcy** [tlaverdure/laravel-echo-server#186]
Hello, I have this error that i'am unable to solve.

`module.js:471
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/laravel-echo-server/dist/database/sqlite.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)`

I tried to uninstall - reinstall. 
I tried to change the name of the directory /node-v48-linux-x64 to /node-v11-linux-x64 because i have this one on my server.

I have this error when i launch laravel-echo-server command.

Does someone knows how to solve it ?

npm -v
3.10.10

nodejs -v
v6.11.1

thanks

**Comment by zassq** [comment]
try go to /usr/local/lib/node_modules/laravel-echo-server/
and run npm install sqlite3 --save

**Comment by solancer** [comment]
has this been taken care of?

**Comment by ElectronicMakerSpace** [comment]
I resolved this problem in raspberry pi 3 b+ with this command: npm install sqlite3 --build-from-source
