### ISSUE TITLE
Error when changing the host name (Error: listen EADDRNOTAVAIL)

### ISSUE THREAD

**Issue by Xationch** [tlaverdure/laravel-echo-server#211]
I got this error when I try to set a differente host name : 

```
✔  Running at app.dev on port 6002
✔  Channels are ready.
✔  Listening for http events...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.10.10:6002
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1243:19)
    at listenInCluster (net.js:1307:12)
    at doListen (net.js:1432:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)

c:\development\php\app>laravel-echo-server start
```

laravel-echo-server.json
```
{
	"authHost": "http://app.dev",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "xxx",
			"key": "xxx"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": "app.dev",
	"port": "6002",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": ""
}
```

The error come only if I change the ```host: null``` to ```host: app.dev```

I try to change the port from 6001 to 6002, 6003, etc. and have the same issue.

It's working if I set the host to null and use the public channel. But I need to set up the same domaine name otherwise I have a CSRF token error when I try to auth.

**Comment by catalinux** [comment]
You need to be able to access http://app.dev from your machine where  you run laravel-echo-server.

**Comment by karunais13** [comment]
Hi, found any solution for this error?

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
