### ISSUE TITLE
Error: Cannot find module  ........./binding/node-v57-linux-x64/node_sqlite3.node'

### ISSUE THREAD

**Issue by ufowiner** [tlaverdure/laravel-echo-server#223]
Error: Cannot find module '/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/dist/database/sqlite.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

**Comment by janva255** [comment]
i fixed it by changing node version

- remove node_modules folder
- npm install -g n
- n v6.11.1
- npm install -g laravel-echo-server
- npm install

**Comment by okaufmann** [comment]
Same Error occurs on windows:

```
Error: Cannot find module '%USERPROFILE%\AppData\Local\Yarn\config\global\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (%USERPROFILE%\AppData\Local\Yarn\config\global\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (%USERPROFILE%\AppData\Local\Yarn\config\global\node_modules\laravel-echo-server\dist\database\sqlite.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

I tried to install sqlite3 separately, but it didn't work.

**Comment by okaufmann** [comment]
This is a problem with sqlite3 itself: https://github.com/mapbox/node-sqlite3/issues/687

**Comment by GaletskyIvan** [comment]
As a temporary solution of this problem, we can install previous version of laravel-echo-server:
> npm install laravel-echo-server@1.3.1 -g

**Comment by jericopulvera** [comment]
I'm having the same problem. Anyone got a solution?

**Comment by jericopulvera** [comment]
find the fixed here #186

**Comment by ravindranrahul** [comment]
For anyone else who comes across this issue, it is caused by changing node versions after installing ghost-cli.

Sqlite3 is a binary dependency that comes with precompiled binaries and downloads the right one for your system on install. If you change the environment, it will look for a different binary, which wasn't downloaded.

This should fix the issue :

`npm un -g laravel-echo-server && npm i -g laravel-echo-server`

**Comment by catalinux** [comment]
Should we add a `Troubleshoot` section in readme.md?

**Comment by ravindranrahul** [comment]
I guess that would help

**Comment by Orinameh** [comment]
I am still having this issue. Can someone please help?

**Comment by ravindranrahul** [comment]
Did [this](https://github.com/tlaverdure/laravel-echo-server/issues/223#issuecomment-354937066) not help?

**Comment by tlaverdure** [comment]
Looks like sqlite doesn't have support for Node 8 yet. So for the time being, sqlite has been moved to a peer dependency and will need to be installed separately if you are using sqlite as a data store. Installing 1.3.5 should fix.
