### ISSUE TITLE
Incorrect JSON request format from API client causes echo-server to crash!

### ISSUE THREAD

**Issue by shajeeck** [tlaverdure/laravel-echo-server#234]
Incorrect JSON request from API client using `http://HOST:6001/apps/APP_ID/events` causes laravel-echo-server to crash and gives error 

`undefined:7
}
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at HttpSubscriber.handleData (/usr/lib/node_modules/laravel-echo-server/dist/subscribers/http-subscriber.js:26:21)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/laravel-echo-server/dist/subscribers/http-subscriber.js:19:59)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)`

this forces to restart echo-server every time any client send incorrect request

to reproduce try sending this request

> {
  "channel": "public-channel",
  "name": "TestEvent",
  "data": {
      "message": "hello"
}

This error should be handled and return a format error as response

**Comment by lucassmacedo** [comment]
i have the same problem

**Comment by tlaverdure** [comment]
Hey there, this issue was opened a while ago. I'm going to close this issue, if this issue still exists, please open a new issue or open a Pull Request.
