### ISSUE TITLE
Cannot find module 'uws'

### ISSUE THREAD

**Issue by ctf0** [tlaverdure/laravel-echo-server#310]
all was working fine until for some reason running with `uws` now gives error

- Laravel v5.6.24
- osx v10.11.6
- node v10.4.1
- npm v6.1.0

```
L A R A V E L  E C H O  S E R V E R

version 1.3.6

⚠ Starting server in DEV mode...

(node:9323) UnhandledPromiseRejectionWarning: Error: Cannot find module 'uws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Server.init (/usr/local/lib/node_modules/laravel-echo-server/node_modules/engine.io/lib/server.js:107:28)
    at new Server (/usr/local/lib/node_modules/laravel-echo-server/node_modules/engine.io/lib/server.js:65:8)
    at Function.attach (/usr/local/lib/node_modules/laravel-echo-server/node_modules/engine.io/lib/engine.io.js:123:16)
    at Server.initEngine (/usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/index.js:310:21)
    at /usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/index.js:295:10
    at Encoder.encode (/usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io-parser/index.js:135:5)
    at Server.listen.Server.attach (/usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/index.js:290:16)
    at new Server (/usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/index.js:59:17)
    at Server (/usr/local/lib/node_modules/laravel-echo-server/node_modules/socket.io/lib/index.js:44:41)
    at Server.httpServer (/usr/local/lib/node_modules/laravel-echo-server/dist/server.js:62:26)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/server.js:29:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9323) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9323) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by breefix** [comment]
Just install uws: [https://www.npmjs.com/package/uws](https://www.npmjs.com/package/uws)

**Comment by ctf0** [comment]
but this is for node, for laravel-echo u actually shouldnt need to install it

**Comment by breefix** [comment]
laravel-echo-server is based on [socket.io](https://github.com/socketio/engine.io), and socket.io from some time requires the installation of uws as a dependency (see `wsEngine` option in the [docs](https://github.com/socketio/engine.io#methods-1)).

> still, installing the npm package doesnt solve it.

Have you installed it globally?

**Comment by ctf0** [comment]
> Have you installed it globally?

this seems to fix the issue, again am not sure why all of a sudden it started to complain about not founding it

**Comment by fannyfan414** [comment]
Can you help me, same problem. install uws: `npm i uws`. Add `"socketio": {
		"wsEngine": "uws"
	},`
But error:

> > laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

version 1.3.7

⚠ Starting server in DEV mode...

{ Error: Cannot find module 'uws'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Server.init (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\engine.io\lib\server.js:107:28)
    at new Server (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\engine.io\lib\server.js:65:8)
    at Function.attach (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\engine.io\lib\engine.io.js:123:16)
    at Server.initEngine (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io\lib\index.js:310:21)
    at C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io\lib\index.js:295:10
    at Encoder.encode (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io-parser\index.js:135:5)
    at Server.listen.Server.attach (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io\lib\index.js:290:16)
    at new Server (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io\lib\index.js:59:17)
    at Server (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\node_modules\socket.io\lib\index.js:44:41)
    at Server.httpServer (C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\server.js:62:26)
    at C:\Users\User\AppData\Roaming\npm\node_modules\laravel-echo-server\dist\server.js:33:31
    at new Promise (<anonymous>) code: 'MODULE_NOT_FOUND' }

**Comment by breefix** [comment]
@fannyfan414 `uws` package is now deprecated ([some info](https://www.reddit.com/r/node/comments/91kgte/uws_has_been_deprecated/)). But you can still install a specific version: `npm i -g uws@10.148.1`
