### ISSUE TITLE
Private channels can run no way on multi server with top domain ?

### ISSUE THREAD

**Issue by callect** [tlaverdure/laravel-echo-server#326]
For excample I have two server on nginx,  one server domain is "www.aaa.com",other server domain is "www.bbb.com".Then how to set laravel-echo-server.json?
I has been tried `"authHost": "http://nginx",`  ， but it will logs 404 like this 
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
I has been tried `"authHost": "http://aaa.com"`， it logs 
```
{ Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80 }
```

**Comment by Ntella** [comment]
You should set host to null , it wil accept requests for any host. And check also Cors

**Comment by asvechkar** [comment]
the same problem: I had publishing app on server with one IP, but access through another IP on router with mapped ports. Error:
[01:27:22] - Error authenticating 1K7v1GZsKswn9oqYAAAB for presence-portal
{ Error: connect ECONNREFUSED *.*.*.*:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '*.*.*.*',
  port: 443 }
Error sending authentication request.
