### ISSUE TITLE
EISDIR: illegal operation error when starting server with HTTPS

### ISSUE THREAD

**Issue by jdbolts** [tlaverdure/laravel-echo-server#335]
When working locally and not on HTTPS the server works fine, however, since moving to live and switching to HTTPS the server will not start and has the following error:

````
{ Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:489:3)
    at tryReadSync (fs.js:328:20)
    at Object.readFileSync (fs.js:365:19)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/server.js:44:26
    at new Promise (<anonymous>)
    at Server.secure (/usr/local/lib/node_modules/laravel-echo-server/dist/server.js:39:16)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/server.js:28:23
    at new Promise (<anonymous>)
    at Server.serverProtocol (/usr/local/lib/node_modules/laravel-echo-server/dist/server.js:26:16)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/server.js:17:19
    at new Promise (<anonymous>)
    at Server.init (/usr/local/lib/node_modules/laravel-echo-server/dist/server.js:16:16)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/echo-server.js:45:26
    at new Promise (<anonymous>)
    at EchoServer.run (/usr/local/lib/node_modules/laravel-echo-server/dist/echo-server.js:41:16)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/cli/cli.js:156:18 errno: -21, syscall: 'read', code: 'EISDIR' }
````

`laravel-echo-server.json` is as follows:

````
{                                                                             
        "authHost": "https://someurl.com",                           
        "authEndpoint": "/broadcasting/auth",                                 
        "clients": [                                                          
                {                                                             
                        "appId": "someappid",                          
                        "key": "somekey"             
                }                                                             
        ],                                                                    
        "database": "redis",                                                  
        "databaseConfig": {                                                   
                "redis": {},                                                  
                "sqlite": {                                                   
                        "databasePath": "/database/laravel-echo-server.sqlite"
                }                                                             
        },                                                                    
        "devMode": true,                                                      
        "host": "https://someurl.com",                                                    
        "port": "6001",                                                       
        "protocol": "https",                                                  
        "socketio": {                                                         
                "wsEngine": "uws"                                             
        },                                                                    
        "sslCertPath": "/etc/nginx/ssl",                                      
        "sslKeyPath": "/etc/nginx/ssl"                                        
}                                                                             
````

**Comment by n0n0n0n0** [comment]
Under path you should specify FULL path to cert and key, NOT a directory.
