### ISSUE TITLE
I need help to debug my 405 Error (now 404)

### ISSUE THREAD

**Issue by pmochine** [tlaverdure/laravel-echo-server#366]
I really don't know what to do anymore. After hours I cannot find my problem.

To make it short. I'm developing a project since last year. In the beginning, I implemented Laravel Echo Server and it worked always. But I don't know when it should be in the last two month suddenly I cannot authenticate my user. 

I did not notice it because I was working on all my little bugs. I have never touched the code for Broadcasting, nor is the route different. But somehow I get this error:

```
⚠ [16:32:06] - _bf6f2ruMazSXJewAAAA could not be authenticated to private-App.User.av0bQG6O7o
<!DOCTYPE html><!--
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException:  in file /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php on line 255
Stack trace:
  1. Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException-&gt;() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:255
  2. Illuminate\Routing\RouteCollection-&gt;methodNotAllowed() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:242
  3. Illuminate\Routing\RouteCollection-&gt;getRouteForMethods() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:176
  4. Illuminate\Routing\RouteCollection-&gt;match() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php:636
  5. Illuminate\Routing\Router-&gt;findRoute() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
  6. Illuminate\Routing\Router-&gt;dispatchToRoute() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php:614
  7. Illuminate\Routing\Router-&gt;dispatch() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
  8. Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
  9. Illuminate\Routing\Pipeline-&gt;Illuminate\Routing\{closure}() /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/nova/src/Http/Middleware/ServeNova.php:26
...
Client can not be authenticated, got HTTP status 405
```

I really don't have any clue what could be the case.

How can I debug this? I don't know at which point it fails. 

And one additional question. Looking at the laravel-echo-server.json file I've "devMode": true,. What does it do? Is there somewhere a log file?

**Comment by tlaverdure** [comment]
Have you tested performing a POST to /broadcasting/auth of your Laravel app to ensure that everything is setup correctly?

**Comment by pmochine** [comment]
@tlaverdure thank you for your fast answer. 

I'm actually not sure how to do it. I just consoled `axios.post('/broadcasting/auth')` but this gives me a 403. 

I want you to show the error from the terminal maybe it helps:

![bildschirmfoto 2018-12-04 um 16 54 44](https://user-images.githubusercontent.com/25006691/49454410-604c8880-f7e5-11e8-845e-22d0e3fb7c07.png)


The setup is untouched and worked all the time. So something in my web.php should be fishy, but I don't get it. The route is listed:

![image](https://user-images.githubusercontent.com/25006691/49454517-97229e80-f7e5-11e8-9ffd-7772b782501c.png)

**Comment by pmochine** [comment]
I'm currently destroying every route I have to a minimum. Now I get the error 404!
 
Besides, I found the debug option now. Maybe it helps you.

```
Starting server in DEV mode...

  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +3ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +0ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/views' +0ms
  express:application set "jsonp callback name" to 'callback' +1ms
  express:router use '/' query +25ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +4ms
  express:router:layer new '/' +1ms
  socket.io:server initializing namespace / +0ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +0ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +1ms
  socket.io:server creating engine.io instance with opts {"path":"/socket.io","initialPacket":["0"]} +2ms
  socket.io:server attaching client serving req handler +35ms
✔  Running at localhost on port 6001
  ioredis:redis status[localhost:6379]: [empty] -> connecting +50ms
✔  Channels are ready.
  ioredis:redis status[localhost:6379]: [empty] -> connecting +5ms
  express:router:route new '/apps/:appId/status' +1ms
  express:router:layer new '/apps/:appId/status' +1ms
  express:router:route get '/apps/:appId/status' +1ms
  express:router:layer new '/' +0ms
  express:router:route new '/apps/:appId/channels' +0ms
  express:router:layer new '/apps/:appId/channels' +1ms
  express:router:route get '/apps/:appId/channels' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/apps/:appId/channels/:channelName' +1ms
  express:router:layer new '/apps/:appId/channels/:channelName' +0ms
  express:router:route get '/apps/:appId/channels/:channelName' +0ms
  express:router:layer new '/' +1ms
  express:router:route new '/apps/:appId/channels/:channelName/users' +0ms
  express:router:layer new '/apps/:appId/channels/:channelName/users' +0ms
  express:router:route get '/apps/:appId/channels/:channelName/users' +0ms
  express:router:layer new '/' +0ms
  express:router:route new '/apps/:appId/events' +0ms
  express:router:layer new '/apps/:appId/events' +1ms
  express:router:route post '/apps/:appId/events' +0ms
  express:router:layer new '/' +0ms
✔  Listening for http events...
  ioredis:redis queue command[0] -> psubscribe(*) +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +31ms
  ioredis:redis write command[0] -> info() +1ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +4ms
  ioredis:redis write command[0] -> info() +0ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +5ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +47ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis write command[0] -> psubscribe(*) +1ms
✔  Listening for redis events...

Server ready!

  engine intercepting request for path "/socket.io/" +0ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=MTwVm_g" +0ms
  engine handshaking client "vYoNj4839ob-XuK3AAAA" +3ms
  engine:socket sending packet "open" ({"sid":"vYoNj4839ob-XuK3AAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}) +0ms
  engine:socket sending packet "message" (0) +0ms
  engine:polling setting request +0ms
  engine:socket flushing buffer to transport +1ms
  engine:polling writing "96:0{"sid":"vYoNj4839ob-XuK3AAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}2:40" +2ms
  engine:socket executing batch send callback +6ms
  socket.io:server incoming connection with id vYoNj4839ob-XuK3AAAA +2s
  socket.io:client connecting to namespace / +0ms
  socket.io:namespace adding socket to nsp / +0ms
  socket.io:socket socket connected - writing packet +0ms
  socket.io:socket joining room vYoNj4839ob-XuK3AAAA +0ms
  socket.io:socket packet already sent in initial handshake +1ms
  socket.io:socket joined room vYoNj4839ob-XuK3AAAA +3ms
  engine intercepting request for path "/socket.io/" +28ms
  engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&t=MTwVn0B&sid=vYoNj4839ob-XuK3AAAA" +0ms
  engine setting new request for existing client +0ms
  engine:polling received "136:42["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}]" +27ms
  engine:socket packet +23ms
  socket.io-parser decoded 2["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}] as {"type":2,"nsp":"/","data":["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}]} +2s
  socket.io:socket got packet {"type":2,"nsp":"/","data":["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}]} +18ms
  socket.io:socket emitting event ["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}] +0ms
  socket.io:socket dispatching an event ["subscribe",{"channel":"private-App.User.p7xbY9b3WL","auth":{"headers":{"X-CSRF-TOKEN":"x5Lf215pEMQO7Utds12SwoLADpS4Cx8QgKtXJnWN"}}}] +0ms
  engine intercepting request for path "/socket.io/" +31ms
  engine handling "GET" http request "/socket.io/?EIO=3&transport=polling&t=MTwVn0D&sid=vYoNj4839ob-XuK3AAAA" +1ms
  engine setting new request for existing client +0ms
  engine:polling setting request +29ms
  engine upgrading existing transport +40ms
  engine:socket might upgrade socket transport from "polling" to "websocket" +68ms
  engine:ws received "2probe" +0ms
  engine:ws writing "3probe" +0ms
  engine:socket writing a noop packet to polling for fast upgrade +111ms
  engine:polling writing "1:6" +151ms
  engine:ws received "5" +107ms
  engine:socket got upgrade packet - upgrading +8ms
  engine:polling closing +11ms
  engine:polling transport discarded - closing right away +0ms
⚠ [19:33:27] - vYoNj4839ob-XuK3AAAA could not be authenticated to private-App.User.p7xbY9b3WL
<!doctype html>
<html lang="en" dir="ltr">
	<head> 404 not found

Client can not be authenticated, got HTTP status 404
  socket.io-parser encoding packet {"type":2,"data":["subscription_error","private-App.User.p7xbY9b3WL",404],"nsp":"/"} +451ms
  socket.io-parser encoded {"type":2,"data":["subscription_error","private-App.User.p7xbY9b3WL",404],"nsp":"/"} as 2["subscription_error","private-App.User.p7xbY9b3WL",404] +0ms
  socket.io:client writing packet ["2[\"subscription_error\",\"private-App.User.p7xbY9b3WL\",404]"] +475ms
  engine:socket sending packet "message" (2["subscription_error","private-App.User.p7xbY9b3WL",404]) +266ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "42["subscription_error","private-App.User.p7xbY9b3WL",404]" +268ms
  engine:ws received "2" +25s
  engine:socket packet +25s
  engine:socket got ping +0ms
  engine:socket sending packet "pong" (undefined) +0ms
  engine:socket flushing buffer to transport +0ms
```

**Comment by pmochine** [comment]
I hope you don't mind @tlaverdure when I comment my process to find this bug. (maybe it's useful for someone)

Now in handler.php I added 

    public function render($request, Exception $exception)
    {
        logger('request', toArray($request));
        logger($exception);

And it results:

```
[2018-12-04 19:58:07] local.DEBUG: request {"attributes":[],"request":[],"query":[],"server":[],"files":[],"cookies":[],"headers":[]} 
[2018-12-04 19:58:07] local.DEBUG: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:179
Stack trace:
#0 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#5 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /Users/shadrix/Dropbox/Business/insta.food/Website_W_Laravel/instafood/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 /Users/shadrix/.composer/vendor/laravel/valet/server.php(147): require('/Users/shadrix/...')
#25 {main}  

```

**Comment by pmochine** [comment]
🎉🎉 I FOUND IT. 

SO don't ask me why, but somehow the code for reading authHost changed. 

Before that I had: 

    "authHost": "https://instafood.test/",
    "authEndpoint": "/broadcasting/auth",

Although this worked one year long, I don't know what happened but now it needs to be

    "authHost": "https://instafood.test",
    "authEndpoint": "/broadcasting/auth",

So without the slash!
