### ISSUE TITLE
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by fauzanmh** [tlaverdure/laravel-echo-server#369]
i try run laravel-echo-server start but i have error like this

L A R A V E L  E C H O  S E R V E R

version 1.5.0

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

solution for me?
#sorryForMyEnglish

**Comment by jeeknowme** [comment]
I also got this error

**Comment by j0hnys** [comment]
If you don't want to use redis set `"redis": false` in laravel-echo-server.json. The init wizard does not does this automatically if you choose sqlite for persistant storage

**Comment by hassanuos** [comment]
I have the same issue. Is there any solution.
![Capture](https://user-images.githubusercontent.com/13483548/54196402-26c1a280-44e3-11e9-9158-df2faa9e191d.PNG)

**Comment by waqas83** [comment]
Seems like Redis is not installed or the Redis server is not running. 
Install a copy from https://redis.io/
And then run the service with "redis-server".
After that you can smoothly run "laravel-echo-server start"

**Comment by hassanuos** [comment]
@waqas83 issue resolved actually the redis was not properly installed on windows 10

**Comment by williamtrindade** [comment]
run the command  
`sudo apt install redis-server`

**Comment by chithresuganesan** [comment]
err

**Comment by chithresuganesan** [comment]
Great...

**Comment by rmodi234** [comment]
you just have to download the Redis server from the website below and execute redis-server.exe to start redis server.

https://riptutorial.com/redis/example/29962/installing-and-running-redis-server-on-windows

**Comment by liyansasongko** [comment]
install redis-server

**Comment by jhoanborges** [comment]
> run the command
> `sudo apt install redis-server`

This is the final solution. thanks

**Comment by theavuthnhel** [comment]
> run the command
> `sudo apt install redis-server`

It was solved. thanks

**Comment by mhemrg** [comment]
As @j0hnys said, you need to add the following config to your `laravel-echo-server.json` file:
```
"subscribers": {
	"http": true,
	"redis": false
}
```

**Comment by theavuthnhel** [comment]
This document is for those who use laravel echo server & nginx & socket.io & redis-server with separated server between client project and redis-server.

**1) Edit `/etc/redis/redis.conf`**

```php
bind 127.0.0.1
supervised no
```

To

```php
bind 0.0.0.0
supervised systemd
```

**2) Update `/etc/systemd/system/redis.service` under `[Service]`**

```php
Type=notify
ExecStart=/usr/bin/redis-server /etc/redis/redis.conf  --supervised systemd
```

**3) Nginx `/etc/nginx/sites-enabled/reverse-proxy.conf`**

```php
server {
  listen        443 ssl;
  listen        [::]:443 ssl;
  server_name   mysitecom;

  error_log     /var/log/nginx/proxy-error.log error;

  # Start the SSL configurations
  ssl                         on;
  ssl_certificate             /etc/nginx/certs/mysitecom.pem;
  ssl_certificate_key         /etc/nginx/certs/mysitecom.key;
  ssl_session_timeout         3m;
  ssl_session_cache           shared:SSL:50m;
  ssl_protocols               TLSv1.1 TLSv1.2;

  # Diffie Hellmann performance improvements
  ssl_ecdh_curve              secp384r1;

  location /socket.io {
    proxy_pass                          http://mysitecom:2096;
    proxy_http_version 1.1;
    proxy_set_header Upgrade            $http_upgrade;
    proxy_set_header Connection         "upgrade";
    proxy_set_header Host               $host;
    proxy_set_header X-Real-IP          $remote_addr;
    proxy_buffers 16 4k;
    proxy_buffer_size 2k;

    proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto  https;
    proxy_set_header X-VerifiedViaNginx yes;
    proxy_read_timeout                  2h;
    proxy_connect_timeout               2h;
    proxy_redirect                      off;
  }
}
```

**4) laravel-echo-server.json**

```php
{
	"authHost": "https://mysitecom",
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "e45c056ec8ca8bd7",
			"key": "88d316b5cccafbc5e905aa9ee13e63f7"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"host": "0.0.0.0",
			"port": "6379"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"devMode": true,
	"host": null,
	"port": "2096",
	"protocol": "https",
	"socketio": {},
	"secureOptions": 67108864,
	"sslCertPath": "/etc/nginx/certs/mysitecom.pem",
	"sslKeyPath": "/etc/nginx/certs/mysitecom.key",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": true,
		"allowOrigin": "*",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}
```

**Note:** for someone who connects DNS with `cloudflare` please change default socket.io port 6001 to the following [here][1].


  [1]: https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-CloudFlare-work-with-

**Comment by Kristoffer95** [comment]
Do this `sudo service redis-server start`

**Comment by weldem** [comment]
`docker pull redis`
`docker run --name redis -d redis`

**Comment by weldem** [comment]
Or you can use docker:
```
docker pull redis
docker run -p 6379:6379 --name redis -d redis
```

**Comment by audelqua** [comment]
I was running docker, So terminating and starting docker fixed my issue

**Comment by MechaMahmud71** [comment]
```
const redis = new Redis({
    host: "localhost",
    port: 6900
})
```
this code runs on my local mechine with redis docker image. But when I dockerize  my nodejs code and try to run the code it shows this error
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6900
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
    
  Redis container is running fine in Port 6900
