### ISSUE TITLE
Unable to join channel. Member data for presence channel missing

### ISSUE THREAD

**Issue by kamaliev** [tlaverdure/laravel-echo-server#413]
> I do the following

`redis-cli -> FLUSHALL`
`laravel-echo-server start`

> I get the following error

L A R A V E L  E C H O  S E R V E R

version 1.5.2

⚠ Starting server in DEV mode...

✔  Running at localhost on port 6001
✔  Channels are ready.
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

[6:31:11 PM] - Sending auth request to: http://localhost/api/broadcasting/auth

[6:31:11 PM] - Sending auth request to: http://localhost/api/broadcasting/auth

[6:31:12 PM] - RZi-54_9fAq_MlctAAAA authenticated for: private-tasks
[6:31:12 PM] - RZi-54_9fAq_MlctAAAA joined channel: private-tasks
[6:31:12 PM] - RZi-54_9fAq_MlctAAAA authenticated for: presence-tasks
Unable to join channel. Member data for presence channel missing
[6:31:12 PM] - RZi-54_9fAq_MlctAAAA joined channel: presence-tasks
[6:31:35 PM] - RZi-54_9fAq_MlctAAAA left channel: private-tasks (transport close)
[6:31:35 PM] - RZi-54_9fAq_MlctAAAA left channel: presence-tasks (transport close)
(node:363) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at /usr/lib/node_modules/laravel-echo-server/dist/channels/presence-channel.js:75:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:363) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:363) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6:31:36 PM] - Sending auth request to: http://localhost/api/broadcasting/auth

[6:31:36 PM] - Sending auth request to: http://localhost/api/broadcasting/auth

[6:31:36 PM] - 72HFMad1Spo6lsncAAAB authenticated for: presence-tasks
Unable to join channel. Member data for presence channel missing
[6:31:36 PM] - 72HFMad1Spo6lsncAAAB joined channel: presence-tasks
[6:31:36 PM] - 72HFMad1Spo6lsncAAAB authenticated for: private-tasks
[6:31:36 PM] - 72HFMad1Spo6lsncAAAB joined channel: private-tasks

> laravel-echo-server.json

{
	"authHost": "http://localhost",
	"authEndpoint": "/api/broadcasting/auth",
	"clients": [
		{
			"appId": "ddca64776e88728d",
			"key": "e07766a0a61037605c3d1d89ff963e2a"
		}
	],
	"database": "redis",
	"databaseConfig": {
        "redis": {
            "port": "6379",
            "host": "localhost"
        }
	},
	"devMode": true,
	"host": null,
	"port": "6001",
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "http://localhost:80",
		"allowMethods": "GET, POST",
		"allowHeaders": "Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id"
	}
}

> channel.php
Broadcast::channel('tasks', function () {
    $jobHelper = new \App\Helpers\TaskHelper();

    $statuses = $jobHelper->getStatuses();

    return filled($statuses) ? $statuses : true;
});

> BroadcastServiceProvider

    public function boot()
    {
        Broadcast::routes(["prefix" => "api", "middleware" => "auth:api"]);

        require base_path('routes/channels.php');
    }

**What am I doing wrong?**

**Comment by xulei2016** [comment]
did you solve it?

**Comment by kamaliev** [comment]
@xulei2016 Yes.

My channels.php

`
Broadcast::channel('tasks', function () {
    $jobHelper = new \App\Helpers\TaskHelper();

    $statuses = $jobHelper->getStatuses();

    return filled($statuses) ? $statuses : ['empty'];
});
`
