### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by NetBT** [tlaverdure/laravel-echo-server#430]
There is an error when I visit laravel-echo-server service of laradock.

 TypeError: Cannot read property 'options' of undefined
    at /usr/src/app/node_modules/laravel-echo-server/dist/server.js:60:37
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/usr/src/app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at query (/usr/src/app/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7

**Comment by latrell** [comment]
I also encountered this problem, and now the production environment has collapsed.

**Comment by 007manu007** [comment]
This is the same issue I am facing when I am trying to hit http://127.0.0.1:6001/apps/a0740b4cddd685c8/status

**Comment by tlaverdure** [comment]
Was able to find the issue. Please try 1.5.7 

Thanks!

**Comment by 007manu007** [comment]
Still not working, I updated the package to 1.5.7. Still showing the same error.

**Comment by 007manu007** [comment]
@tlaverdure any update on this issue?

**Comment by tlaverdure** [comment]
I'm not seeing that error. Was able to reproduce and fixed:
https://github.com/tlaverdure/laravel-echo-server/commit/346a1476e3e34b0655c7076e4d9515bc37ce0a3e

Maybe the version you're using is being cached?

**Comment by appdrops** [comment]
I was getting the error. Installed 1.5.7 and is now fixed

**Comment by 007manu007** [comment]
@appdrops what all you did to fix the issue? I mean after update the version to 1.5.7

**Comment by appdrops** [comment]
@007manu007 it worked straight away. Check all your settings, maybe you changed your config from standard. Also, restart server etc.

**Comment by 007manu007** [comment]
Thank you, This issue is fixed. Now I want to know will it work as a socket, emit and listen all will work? How I able to configure it with the mobile application? Thanks!
