### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError with version 1.5.8

### ISSUE THREAD

**Issue by a-h-abid** [tlaverdure/laravel-echo-server#440]
Hi, seems like some sort of error is being generated... Occasionally the broadcast server fails to work...

```
Channel: PresenceChannelUpdated
Event: [object Object]
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'broadcast' of undefined
    at PresenceChannel.onJoin (/usr/local/lib/node_modules/laravel-echo-server/dist/channels/presence-channel.js:85:14)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/channels/presence-channel.js:59:27
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Channel: PresenceChannelUpdated
Event: [object Object]
[5:32:39 PM] - SFr673ZV_OBqOQMnAAAF authenticated for: presence-App.Session.4
[5:32:39 PM] - SFr673ZV_OBqOQMnAAAF joined channel: presence-App.Session.4
Channel: PresenceChannelUpdated
Event: [object Object]
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'broadcast' of undefined
    at PresenceChannel.onJoin (/usr/local/lib/node_modules/laravel-echo-server/dist/channels/presence-channel.js:85:14)
    at /usr/local/lib/node_modules/laravel-echo-server/dist/channels/presence-channel.js:59:27
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by jhoanborges** [comment]
same here

**Comment by jhoanborges** [comment]
> I got that warning too. That happens because dont have a "try catch" in the code of the promise. I just put a "try catch" in the code to stop that warning. Worked nicely.

which file?

**Comment by huiwanggo** [comment]
same here，how to solve it?
