### ISSUE TITLE
laravel-echo-server start report an error

### ISSUE THREAD

**Issue by jxl1996** [tlaverdure/laravel-echo-server#450]
L A R A V E L  E C H O  S E R V E R

version 1.5.9

⚠ Starting server in DEV mode...

/usr/lib/node_modules/laravel-echo-server/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by dmsysop** [comment]
same problem here


L A R A V E L  E C H O  S E R V E R

version 1.5.9

âš  Starting server in DEV mode...

/usr/lib/node_modules/laravel-echo-server/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)

**Comment by AshXing** [comment]
I solved it by upgrade node to latest version:

sudo npm install n -g
sudo n latest

**Comment by IGSteven** [comment]
ah shit, i should have commented on this days ago, Yeah i fixed it the same way

**Comment by dmsysop** [comment]
me too... upgrade the f*ck damn version of node!!
