### ISSUE TITLE
1.6.0 bug

### ISSUE THREAD

**Issue by infister** [tlaverdure/laravel-echo-server#473]
Every few minutes a warning appears:

```
(node:1902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
at /usr/lib/node_modules/laravel-echo-server-socketio/dist/channels/presence-channel.js:71:31
at Array.filter (<anonymous>)
at /usr/lib/node_modules/laravel-echo-server-socketio/dist/channels/presence-channel.js:71:81
(node:1902) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'socketId' of undefined
```

I am using presence channels.

**Comment by jhoanborges** [comment]
same here

**Comment by AhW00** [comment]
same here

**Comment by jasparfitt** [comment]
I'm also experiencing this issue, looks like there is even a pull request with a fix in https://github.com/tlaverdure/laravel-echo-server/pull/535 would be great if that could make it's way into a version
