### ISSUE TITLE
AWS Redis Cluster not working

### ISSUE THREAD

**Issue by razibchamp** [tlaverdure/laravel-echo-server#479]
It was running fine on local machine but not working on production as i am using AWS redis cluster there. Although It is showing "✔  Listening for redis events..." .

L A R A V E L  E C H O  S E R V E R

version 1.6.0

Starting server...

✔  Running at localhost on port 6001
✔  Listening for http events...
✔  Listening for redis events...

Server ready!

Unhandled rejection ReplyError: MOVED 12302 SOME_IP:6379
    at JavascriptRedisParser.returnError (/usr/lib/node_modules/laravel-echo-server/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/usr/lib/node_modules/laravel-echo-server/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/usr/lib/node_modules/laravel-echo-server/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at Socket.emit (events.js:321:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by mohamadchoker** [comment]
same here any solution?

**Comment by razibchamp** [comment]
@mohamadchoker are using laravel broadcasting or caching ?

**Comment by mohamadchoker** [comment]
@razibchamp broadcasting

**Comment by razibchamp** [comment]
Laravel broadcasting doesn't support redis cluster. I used local redis in EC2 instead of aws redis cluster.

**Comment by srhtylmz19** [comment]
@razibchamp are we sure about that ? trying to connect with remote redis server with laravel echo server?
