### ISSUE TITLE
Cannot find module spawn-sync@1.0.15 postinstall: `node postinstall`

### ISSUE THREAD

**Issue by skeeith** [tlaverdure/laravel-echo-server#486]
Does anyone know how to fix this issue?

Ubuntu 18.04.4 LTS
Node v12.16.1
npm v6.13.4

```
/root/.npm-global/bin/laravel-echo-server -> /root/.npm-global/lib/node_modules/laravel-echo-server/bin/server.js

> spawn-sync@1.0.15 postinstall /root/.npm-global/lib/node_modules/laravel-echo-server/node_modules/spawn-sync
> node postinstall

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/root/.npm-global/lib/node_modules/laravel-echo-server/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-28T09_01_48_305Z-debug.log
```

**Comment by skeeith** [comment]
I found the answer, NEVER install it on a root user.
