### ISSUE TITLE
@ECHO OFF - Invalid or unexpected token 

### ISSUE THREAD

**Issue by smaqeelkazmi** [tlaverdure/laravel-echo-server#534]
I'm just trying to run `laravel-echo-server` using `pm2`, but it throws following error:

```
C:\USERS\HP\APPDATA\ROAMING\NPM\LARAVEL-ECHO-SERVER.CMD:1
1|my-app   | @ECHO off
1|my-app   | ^
1|my-app   | 
1|my-app   | SyntaxError: Invalid or unexpected token
1|my-app   |     at wrapSafe (internal/modules/cjs/loader.js:1072:16)
1|my-app   |     at Module._compile (internal/modules/cjs/loader.js:1122:27)
1|my-app   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
1|my-app   |     at Module.load (internal/modules/cjs/loader.js:1002:32)
1|my-app   |     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
1|my-app   |     at C:\Users\HP\AppData\Roaming\npm\node_modules\pm2\lib\ProcessContainer.js:303:25
1|my-app   |     at wrapper (C:\Users\HP\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\once.js:12:16)
1|my-app   |     at next (C:\Users\HP\AppData\Roaming\npm\node_modules\pm2\node_modules\async\waterfall.js:96:20)
1|my-app   |     at C:\Users\HP\AppData\Roaming\npm\node_modules\pm2\node_modules\async\internal\onlyOnce.js:12:16
1|my-app   |     at WriteStream.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\pm2\lib\Utility.js:186:13)
```

Here is the configuration for running the server using PM2(`laravel-echo-server.yml`):

```
apps:
  - name: my-app
    script: laravel-echo-server
    instances: 1
    args:
      - start
```

Can anyone please help me that how I can run `laravel-echo-server` using `PM2 `on `Windows 10` or if there is any other possible way to run it in the production?

Thanks in advance.

**Comment by smaqeelkazmi** [comment]
any one there to help me out?

**Comment by lpettecrew** [comment]
same here - any chance you have a fix? lmao

**Comment by resulparahadow** [comment]
I have the same problem. I have searched but I couldn't solve.

**Comment by derciesto** [comment]
same here

**Comment by derciesto** [comment]
use this [node-widows](https://www.npmjs.com/package/node-windows) its work same as pm2.
