### ISSUE TITLE
npx laravel-echo-server start

### ISSUE THREAD

**Issue by zy77777** [tlaverdure/laravel-echo-server#612]
vagrant@homestead:~/code/processmaker$ npx laravel-echo-server start

L A R A V E L  E C H O  S E R V E R

version 1.6.3

Starting server...

✔  Running at localhost on port 6001
✔  Listening for http events...
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/home/vagrant/code/processmaker/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/vagrant/code/processmaker/node_modules/redis-parser/lib/parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.
    at parseError (/home/vagrant/code/processmaker/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/vagrant/code/processmaker/node_modules/redis-parser/lib/parser.js:302:14)
✔  Listening for redis events...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Redis could not subscribe.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

laravel-echo-server.json
{
	"authEndpoint": "/broadcasting/auth",
	"clients": [
		{
			"appId": "0fd1f7a0ce0d527c",
			"key": "21a795019957dde6bcd96142e05d4b10"
		}
	],
	"database": "redis",
	"databaseConfig": {
		"redis": {
			"port": 6379,
			"host": "192.168.10.10",
			"authPass": "homestead"
		},
		"sqlite": {
			"databasePath": "/database/laravel-echo-server.sqlite"
		}
	},
	"protocol": "http",
	"socketio": {},
	"sslCertPath": "",
	"sslKeyPath": "",
	"sslCertChainPath": "",
	"sslPassphrase": "",
	"subscribers": {
		"http": true,
		"redis": true
	},
	"apiOriginAllow": {
		"allowCors": false,
		"allowOrigin": "",
		"allowMethods": "",
		"allowHeaders": ""
	}
}

**Comment by shifas-cubet** [comment]
Same error for me
