### ISSUE TITLE
cannot find module '../dist/cli' after updating to master

### ISSUE THREAD

**Issue by vesper8** [tlaverdure/laravel-echo-server#89]
So I wanted to use one of your hotfixes 

https://github.com/tlaverdure/laravel-echo-server/pull/86

so I installed the latest master by running this command:

sudo npm install -g git://github.com/tlaverdure/laravel-echo-server.git#master

Which resulted in this version being installed

laravel-echo-server@1.1.0  (git://github.com/tlaverdure/laravel-echo-server.git#7cd21c8bbd4201f87f9deed963be5bf19206735c)

I realize now that the hotfix I want hasn't been merged yet.. but anyway..

Now when I try to run laravel-echo-server start I get

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../dist/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/bin/server.js:10:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

tried to run sudo npm update -g but that didn't help

any idea? Thanks

**Comment by tlaverdure** [comment]
Master has been updated and seems to be working fine for me. #86 has not been merged yet but will be once conflicts are resolved. .

**Comment by vesper8** [comment]
I'm still getting this error. Using the latest master because I want the above fix

ran 
```
sudo npm install -g git://github.com/tlaverdure/laravel-echo-server.git#e80f3b08fe47a101c8f6eef3f7aa3050fe805191
```

then

```
$ laravel-echo-server start
module.js:471
    throw err;
    ^

Error: Cannot find module '../dist/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/laravel-echo-server/bin/server.js:10:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

any idea?

**Comment by vesper8** [comment]
pretty boggled by this issue so I am doing a folder comparison of the latest commit vs the version you get when you don't specify a commit

ie

sudo npm install -g git://github.com/tlaverdure/laravel-echo-server.git#e80f3b08fe47a101c8f6eef3f7aa3050fe805191
vs
sudo npm install laravel-echo-server

and sure enough the first command gets you a folder who's dist folder is missing everything as you can see in the screenshot below

what am I not getting here? What is the proper way of getting the latest master using npm?

<img width="1017" alt="screenshot 2017-01-11 18 14 06" src="https://cloud.githubusercontent.com/assets/816028/21846445/c5e75914-d829-11e6-8395-5a2c0c6538fd.png">

**Comment by tlaverdure** [comment]
That is because the src folder is ignored in .npmignore. Npm has the latest version 1.1.3, I would install from there.
